In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('../data/iris.csv')

In [5]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [84]:
X=df.iloc[:,3:5].to_numpy()
y= df['Species'].replace({'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2}).to_numpy()

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=123, shuffle=True)

In [100]:
def euclidian(x1,x2):
    return np.sqrt(np.sum(np.square(x1-x2)))

In [110]:
print(X_train[0])
print(X_test[0])

[5.1 2.4]
[4.9 1.5]


In [113]:
np.sqrt((0.2**2)+(0.9**2))

0.9219544457292888

In [114]:
euclidian(X_test[0],X_train[0])

0.9219544457292885

In [117]:
dist_arr_0 = np.array([euclidian(X_train[i],X_test[0]) for i in range(X_train.shape[0])])

In [121]:
dist_arr_0

array([0.92195445, 1.14017543, 0.92195445, 3.60555128, 3.82753184,
       0.53851648, 3.35261092, 3.67695526, 0.2       , 0.31622777,
       0.92195445, 1.48660687, 0.4472136 , 0.50990195, 0.89442719,
       3.79473319, 1.        , 0.76157731, 3.57351368, 3.54682957,
       0.76157731, 0.63245553, 1.86815417, 2.15406592, 3.19530906,
       0.4       , 1.3       , 0.36055513, 3.76961536, 0.90553851,
       0.2236068 , 0.2236068 , 3.54682957, 0.92195445, 0.41231056,
       3.42052628, 3.73363094, 0.92195445, 0.3       , 1.48660687,
       3.92173431, 3.7       , 1.17046999, 3.47850543, 0.31622777,
       0.78102497, 3.54682957, 0.9486833 , 3.57351368, 3.4176015 ,
       0.2236068 , 4.11096096, 3.64005494, 0.36055513, 1.43178211,
       0.50990195, 1.31529464, 1.07703296, 3.64005494, 3.79473319,
       0.14142136, 0.70710678, 3.67695526, 3.64005494, 0.72801099,
       0.41231056, 0.63245553, 1.16619038, 0.        , 0.9486833 ,
       0.82462113, 1.80277564, 3.64005494, 3.64005494, 0.7    

In [122]:
np.argsort(dist_arr_0)

array([ 68,  60,   8,  99,  50,  31,  30,  97,  38,  44, 103,   9,  27,
        91,  53,  87, 102,  80,  85,  25,  34,  65,  12,  83,  98,  94,
        55,  13,   5,  89,  78,  66,  21,  76,  74,  61,  95,  64,  20,
        17,  45,  70,  14,  29,  33,   0,   2,  10,  37,  93,  82,  47,
        69,  16,  57,  75,  86,  77,   1,  67,  42,  88,  26,  56,  54,
        39,  11, 104,  96,  71,  22, 101,  23,  24,   6,  49,  35,  43,
        19,  32,  46,  18,  48,   3,  63,  52,  58,  72,  79,  73,  62,
        90,   7, 100,  41,  36,  92,  84,  28,  59,  15,  81,   4,  40,
        51], dtype=int64)

In [ ]:
dist_arr_0[]

In [120]:
np.sort(dist_arr_0)

array([0.        , 0.14142136, 0.2       , 0.2236068 , 0.2236068 ,
       0.2236068 , 0.2236068 , 0.3       , 0.3       , 0.31622777,
       0.31622777, 0.31622777, 0.36055513, 0.36055513, 0.36055513,
       0.4       , 0.4       , 0.4       , 0.4       , 0.4       ,
       0.41231056, 0.41231056, 0.4472136 , 0.4472136 , 0.4472136 ,
       0.50990195, 0.50990195, 0.50990195, 0.53851648, 0.56568542,
       0.58309519, 0.63245553, 0.63245553, 0.67082039, 0.7       ,
       0.70710678, 0.72801099, 0.72801099, 0.76157731, 0.76157731,
       0.78102497, 0.82462113, 0.89442719, 0.90553851, 0.92195445,
       0.92195445, 0.92195445, 0.92195445, 0.92195445, 0.94339811,
       0.94339811, 0.9486833 , 0.9486833 , 1.        , 1.07703296,
       1.13137085, 1.14017543, 1.14017543, 1.14017543, 1.16619038,
       1.17046999, 1.28062485, 1.3       , 1.31529464, 1.43178211,
       1.48660687, 1.48660687, 1.56204994, 1.67630546, 1.80277564,
       1.86815417, 1.94164878, 2.15406592, 3.19530906, 3.35261

In [ ]:
def K_NN(K,x,x_train):
    
    

In [101]:
euclidian(np.array([1,2,3]),np.array([1,2,3]))

0.0

In [ ]:
class K_NN_Classifier:
    
    def __init__(self,K):
        self.K = K
        
    def fit(X_train):
        
    def predict(x1):
        return y_hat