In [2]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
a=np.ones((2,3))

In [8]:
a.shape

(2, 3)

In [11]:
a.ndim

2

In [13]:
a.size

6

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
6*np.eye(3)

array([[6., 0., 0.],
       [0., 6., 0.],
       [0., 0., 6.]])

In [23]:
np.diag((3,3,4))

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [28]:
np.arange(4.,10.1)

array([ 4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [36]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
ary = np.array([1, 2, 3])
ary[0]


1

In [45]:
ary[1:]

array([2, 3])

In [46]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

ary[0, 0] # upper left


1

In [49]:
ary[-1,-1]

6

In [50]:
ary[0]

array([1, 2, 3])

In [59]:
ary[0:1,:]

array([[1, 2, 3]])

In [60]:
ary[:,1:2]

array([[2],
       [5]])

In [70]:
lst = [[1, 2, 3], [4, 5, 6]]

In [62]:
lst

[[1, 2, 3], [4, 5, 6]]

In [65]:
for i in range(2):
    for j in range(3):
        lst[i][j]+=1
        
lst

[[2, 3, 4], [5, 6, 7]]

In [75]:
for i,x in enumerate(lst):
    print(i,x)
    for j,y in enumerate(x):
        print(y)
        

0 [1, 2, 3]
1
2
3
1 [4, 5, 6]
4
5
6


In [72]:
enumerate(lst)

## List comprehension

In [77]:
print(lst[0])
print(lst[1])

[1, 2, 3]
[4, 5, 6]


In [78]:
a=[1,2,3]

In [79]:
a

[1, 2, 3]

In [81]:
[i for i in a]

[1, 2, 3]

In [83]:
[(i) for i in lst]

[[1, 2, 3], [4, 5, 6]]

In [84]:
[(row) for row in lst]

[[1, 2, 3], [4, 5, 6]]

In [88]:
[[cell+1 for cell in row] for row in lst]

[[2, 3, 4], [5, 6, 7]]

In [91]:
np.array(lst)+1

array([[2, 3, 4],
       [5, 6, 7]])

In [92]:
np.add(np.array(lst),3)

array([[4, 5, 6],
       [7, 8, 9]])

In [94]:
ary = np.array([[1, 2, 3], 
                [4, 5, 6]])

ary=np.ones((3,4,5))
ary

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])